spring.application.name=ZohoSync

server.port=8085

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=XFACTORPRO
spring.datasource.password=XFACTORPRO
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

zoho.client.id=1000.3RBAR7MN5T103VTNFO589UBLTMKTZV
zoho.client.secret=17b21073742aefe0da98a9c5a1456994749b887004
zoho.refresh.token=1000.8544384ac861bcdd5b628370cb8bb88a.520e3f197177c55639815b8de4093dc4

zoho.leave.client.id=1000.3RBAR7MN5T103VTNFO589UBLTMKTZV
zoho.leave.client.secret=17b21073742aefe0da98a9c5a1456994749b887004
zoho.leave.refresh.token=1000.a6a44dee99fd1838f8edafdb724c93ca.09ca849b9059ca31159b6947b5bc0fed
zoho.leave.token.url=https://accounts.zoho.com/oauth/v2/token

zoho.token.url=https://accounts.zoho.com/oauth/v2/token
zoho.employee.url=https://people.zoho.com/people/api/forms/employee/getRecords

spring.jackson.default-property-inclusion=non_null