spring.application.name=ZohoSync

server.port=8085

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=XFACTORPRO
spring.datasource.password=XFACTORPRO
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

zoho.client.id=YOUR_CLIENT_ID
zoho.client.secret=YOUR_CLIENT_SECRET
zoho.refresh.token=YOUR_REFRESH_TOKEN

zoho.leave.client.id=YOUR_CLIENT_ID
zoho.leave.client.secret=YOUR_CLIENT_SECRET
zoho.leave.refresh.token=YOUR_REFRESH_TOKEN
zoho.leave.token.url=https://accounts.zoho.com/oauth/v2/token

zoho.token.url=https://accounts.zoho.com/oauth/v2/token
zoho.employee.url=https://people.zoho.com/people/api/forms/employee/getRecords

spring.jackson.default-property-inclusion=non_null